spring:
  application:
    name: identity-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5433/flowguard_identity
    username: flowguard
    password: flowguard

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5433/flowguard_identity
    user: flowguard
    password: flowguard
    locations: classpath:db/migration

server:
  port: 8081

api:
  endpoint:
    base-url: /api/v1

security:
  jwt:
    public-key: classpath:certs/public.pem
    private-key: classpath:certs/private.pem
    issuer: flowguard-identity-service
    access-token-expiration: 2h

logging:
  level:
    org.springframework.r2dbc.core: INFO
