spring:
  application:
    name: identity-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5433/flowguard_identity
    username: flowguard
    password: flowguard

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5433/flowguard_identity
    user: flowguard
    password: flowguard
    locations: classpath:db/migration

  server:
    port: 8081
